[2023-06-30T07:29:28.939+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: order-letter_NER.post_to_dynamics_task manual__2023-06-30T06:57:15.409939+00:00 [queued]>
[2023-06-30T07:29:28.964+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: order-letter_NER.post_to_dynamics_task manual__2023-06-30T06:57:15.409939+00:00 [queued]>
[2023-06-30T07:29:28.965+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-30T07:29:29.008+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): post_to_dynamics_task> on 2023-06-30 06:57:15.409939+00:00
[2023-06-30T07:29:29.019+0000] {standard_task_runner.py:57} INFO - Started process 5000 to run task
[2023-06-30T07:29:29.024+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'order-letter_NER', 'post_to_dynamics_task', 'manual__2023-06-30T06:57:15.409939+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/order-letter-extraction.py', '--cfg-path', '/tmp/tmpbldkiqaf']
[2023-06-30T07:29:29.028+0000] {standard_task_runner.py:85} INFO - Job 63: Subtask post_to_dynamics_task
[2023-06-30T07:29:29.142+0000] {task_command.py:410} INFO - Running <TaskInstance: order-letter_NER.post_to_dynamics_task manual__2023-06-30T06:57:15.409939+00:00 [running]> on host f7b244b51c6e
[2023-06-30T07:29:29.525+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Abin Jilson' AIRFLOW_CTX_DAG_ID='order-letter_NER' AIRFLOW_CTX_TASK_ID='post_to_dynamics_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-30T06:57:15.409939+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-30T06:57:15.409939+00:00'
[2023-06-30T07:29:33.177+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/order-letter-extraction.py", line 171, in dynamics_upload_main
    "quantity": quantity_list[i],
IndexError: string index out of range
[2023-06-30T07:29:33.201+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=order-letter_NER, task_id=post_to_dynamics_task, execution_date=20230630T065715, start_date=20230630T072928, end_date=20230630T072933
[2023-06-30T07:29:33.229+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 63 for task post_to_dynamics_task (string index out of range; 5000)
[2023-06-30T07:29:33.255+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-30T07:29:33.279+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
