[2023-06-29T08:37:02.015+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: order-letter_NER.read_order_from_mail manual__2023-06-29T08:36:57.167062+00:00 [queued]>
[2023-06-29T08:37:02.028+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: order-letter_NER.read_order_from_mail manual__2023-06-29T08:36:57.167062+00:00 [queued]>
[2023-06-29T08:37:02.029+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-29T08:37:02.052+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): read_order_from_mail> on 2023-06-29 08:36:57.167062+00:00
[2023-06-29T08:37:02.062+0000] {standard_task_runner.py:57} INFO - Started process 3039 to run task
[2023-06-29T08:37:02.067+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'order-letter_NER', 'read_order_from_mail', 'manual__2023-06-29T08:36:57.167062+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/order-letter-extraction.py', '--cfg-path', '/tmp/tmpmfatnu26']
[2023-06-29T08:37:02.071+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask read_order_from_mail
[2023-06-29T08:37:02.156+0000] {task_command.py:410} INFO - Running <TaskInstance: order-letter_NER.read_order_from_mail manual__2023-06-29T08:36:57.167062+00:00 [running]> on host 0eb747d9e0f2
[2023-06-29T08:37:02.275+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Abin Jilson' AIRFLOW_CTX_DAG_ID='order-letter_NER' AIRFLOW_CTX_TASK_ID='read_order_from_mail' AIRFLOW_CTX_EXECUTION_DATE='2023-06-29T08:36:57.167062+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-29T08:36:57.167062+00:00'
[2023-06-29T10:31:38.003+0000] {local_task_job_runner.py:291} WARNING - State of this instance has been externally set to None. Terminating instance.
[2023-06-29T10:31:38.014+0000] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 3039. PIDs of all processes in the group: [3039]
[2023-06-29T10:31:38.015+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 3039
[2023-06-29T10:31:38.016+0000] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-06-29T10:31:38.038+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/order-letter-extraction.py", line 63, in read_order_from_mail
    # Wait for 10 seconds before checking again
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1519, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-06-29T10:31:38.051+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=order-letter_NER, task_id=read_order_from_mail, execution_date=20230629T083657, start_date=20230629T083702, end_date=20230629T103138
[2023-06-29T10:31:38.092+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 18 for task read_order_from_mail (Task received SIGTERM signal; 3039)
[2023-06-29T10:31:38.169+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=3039, status='terminated', exitcode=1, started='08:37:01') (3039) terminated with exit code 1
