[2023-06-30T10:35:32.570+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: order-letter_NER.post_to_dynamics_task manual__2023-06-30T10:33:13.622748+00:00 [queued]>
[2023-06-30T10:35:32.592+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: order-letter_NER.post_to_dynamics_task manual__2023-06-30T10:33:13.622748+00:00 [queued]>
[2023-06-30T10:35:32.593+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-30T10:35:32.640+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): post_to_dynamics_task> on 2023-06-30 10:33:13.622748+00:00
[2023-06-30T10:35:32.653+0000] {standard_task_runner.py:57} INFO - Started process 12172 to run task
[2023-06-30T10:35:32.662+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'order-letter_NER', 'post_to_dynamics_task', 'manual__2023-06-30T10:33:13.622748+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/order-letter-extraction.py', '--cfg-path', '/tmp/tmp2v1r8tro']
[2023-06-30T10:35:32.666+0000] {standard_task_runner.py:85} INFO - Job 72: Subtask post_to_dynamics_task
[2023-06-30T10:35:32.800+0000] {task_command.py:410} INFO - Running <TaskInstance: order-letter_NER.post_to_dynamics_task manual__2023-06-30T10:33:13.622748+00:00 [running]> on host f7b244b51c6e
[2023-06-30T10:35:33.003+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Abin Jilson' AIRFLOW_CTX_DAG_ID='order-letter_NER' AIRFLOW_CTX_TASK_ID='post_to_dynamics_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-30T10:33:13.622748+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-30T10:33:13.622748+00:00'
[2023-06-30T10:35:33.006+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/order-letter-extraction.py", line 163, in dynamics_upload_main
    product_list = json.loads(product_list)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
[2023-06-30T10:35:33.020+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=order-letter_NER, task_id=post_to_dynamics_task, execution_date=20230630T103313, start_date=20230630T103532, end_date=20230630T103533
[2023-06-30T10:35:33.044+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 72 for task post_to_dynamics_task (Expecting value: line 1 column 2 (char 1); 12172)
[2023-06-30T10:35:33.081+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-30T10:35:33.119+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
