[2023-06-30T04:25:41.258+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: order-letter_NER.read_order_from_mail scheduled__2023-06-29T00:00:00+00:00 [queued]>
[2023-06-30T04:25:41.276+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: order-letter_NER.read_order_from_mail scheduled__2023-06-29T00:00:00+00:00 [queued]>
[2023-06-30T04:25:41.277+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 6
[2023-06-30T04:25:41.320+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): read_order_from_mail> on 2023-06-29 00:00:00+00:00
[2023-06-30T04:25:41.343+0000] {standard_task_runner.py:57} INFO - Started process 428 to run task
[2023-06-30T04:25:41.345+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'order-letter_NER', 'read_order_from_mail', 'scheduled__2023-06-29T00:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/order-letter-extraction.py', '--cfg-path', '/tmp/tmp_e_3g14p']
[2023-06-30T04:25:41.349+0000] {standard_task_runner.py:85} INFO - Job 49: Subtask read_order_from_mail
[2023-06-30T04:25:41.443+0000] {task_command.py:410} INFO - Running <TaskInstance: order-letter_NER.read_order_from_mail scheduled__2023-06-29T00:00:00+00:00 [running]> on host f7b244b51c6e
[2023-06-30T04:25:41.734+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Abin Jilson' AIRFLOW_CTX_DAG_ID='order-letter_NER' AIRFLOW_CTX_TASK_ID='read_order_from_mail' AIRFLOW_CTX_EXECUTION_DATE='2023-06-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-29T00:00:00+00:00'
[2023-06-30T04:29:56.555+0000] {logging_mixin.py:149} INFO - An error occurred: [Errno -3] Temporary failure in name resolution
[2023-06-30T04:30:23.413+0000] {logging_mixin.py:149} INFO - An error occurred: [Errno -3] Temporary failure in name resolution
[2023-06-30T04:31:03.513+0000] {local_task_job_runner.py:291} WARNING - State of this instance has been externally set to None. Terminating instance.
[2023-06-30T04:31:03.542+0000] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 428. PIDs of all processes in the group: [428]
[2023-06-30T04:31:03.561+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 428
[2023-06-30T04:31:03.562+0000] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-06-30T04:31:03.566+0000] {logging_mixin.py:149} INFO - An error occurred: Task received SIGTERM signal
[2023-06-30T04:32:03.444+0000] {process_utils.py:149} WARNING - process psutil.Process(pid=428, name='airflow task ru', status='sleeping', started='04:25:40') did not respond to SIGTERM. Trying SIGKILL
[2023-06-30T04:32:03.449+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGKILL to group 428
[2023-06-30T04:32:03.543+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=428, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='04:25:40') (428) terminated with exit code Negsignal.SIGKILL
[2023-06-30T04:32:03.544+0000] {standard_task_runner.py:172} ERROR - Job 49 was killed before it finished (likely due to running out of memory)
