[2023-06-30T14:44:36.037+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: order-letter_NER.post_to_dynamics_task manual__2023-06-30T12:56:59.819289+00:00 [queued]>
[2023-06-30T14:44:36.051+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: order-letter_NER.post_to_dynamics_task manual__2023-06-30T12:56:59.819289+00:00 [queued]>
[2023-06-30T14:44:36.052+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 6
[2023-06-30T14:44:36.080+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): post_to_dynamics_task> on 2023-06-30 12:56:59.819289+00:00
[2023-06-30T14:44:36.095+0000] {standard_task_runner.py:57} INFO - Started process 21695 to run task
[2023-06-30T14:44:36.101+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'order-letter_NER', 'post_to_dynamics_task', 'manual__2023-06-30T12:56:59.819289+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/order-letter-extraction.py', '--cfg-path', '/tmp/tmpzhm41m_6']
[2023-06-30T14:44:36.104+0000] {standard_task_runner.py:85} INFO - Job 129: Subtask post_to_dynamics_task
[2023-06-30T14:44:36.174+0000] {task_command.py:410} INFO - Running <TaskInstance: order-letter_NER.post_to_dynamics_task manual__2023-06-30T12:56:59.819289+00:00 [running]> on host f7b244b51c6e
[2023-06-30T14:44:36.281+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Abin Jilson' AIRFLOW_CTX_DAG_ID='order-letter_NER' AIRFLOW_CTX_TASK_ID='post_to_dynamics_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-30T12:56:59.819289+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-30T12:56:59.819289+00:00'
[2023-06-30T14:44:36.284+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/order-letter-extraction.py", line 163, in dynamics_upload_main
    xcom_value = task_instance.xcom_pull(
AttributeError: 'str' object has no attribute 'xcom_pull'
[2023-06-30T14:44:36.297+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=order-letter_NER, task_id=post_to_dynamics_task, execution_date=20230630T125659, start_date=20230630T144436, end_date=20230630T144436
[2023-06-30T14:44:36.316+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 129 for task post_to_dynamics_task ('str' object has no attribute 'xcom_pull'; 21695)
[2023-06-30T14:44:36.354+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-30T14:44:36.393+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
