[2023-06-30T11:31:48.018+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: order-letter_NER.post_to_dynamics_task manual__2023-06-30T11:18:42.905527+00:00 [queued]>
[2023-06-30T11:31:48.030+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: order-letter_NER.post_to_dynamics_task manual__2023-06-30T11:18:42.905527+00:00 [queued]>
[2023-06-30T11:31:48.030+0000] {taskinstance.py:1308} INFO - Starting attempt 6 of 6
[2023-06-30T11:31:48.052+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): post_to_dynamics_task> on 2023-06-30 11:18:42.905527+00:00
[2023-06-30T11:31:48.058+0000] {standard_task_runner.py:57} INFO - Started process 14377 to run task
[2023-06-30T11:31:48.062+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'order-letter_NER', 'post_to_dynamics_task', 'manual__2023-06-30T11:18:42.905527+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/order-letter-extraction.py', '--cfg-path', '/tmp/tmp76633084']
[2023-06-30T11:31:48.065+0000] {standard_task_runner.py:85} INFO - Job 86: Subtask post_to_dynamics_task
[2023-06-30T11:31:48.129+0000] {task_command.py:410} INFO - Running <TaskInstance: order-letter_NER.post_to_dynamics_task manual__2023-06-30T11:18:42.905527+00:00 [running]> on host f7b244b51c6e
[2023-06-30T11:31:48.257+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Abin Jilson' AIRFLOW_CTX_DAG_ID='order-letter_NER' AIRFLOW_CTX_TASK_ID='post_to_dynamics_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-30T11:18:42.905527+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-30T11:18:42.905527+00:00'
[2023-06-30T11:31:48.260+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/order-letter-extraction.py", line 163, in dynamics_upload_main
    product_list = json.loads(product_list)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
[2023-06-30T11:31:48.273+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=order-letter_NER, task_id=post_to_dynamics_task, execution_date=20230630T111842, start_date=20230630T113148, end_date=20230630T113148
[2023-06-30T11:31:48.296+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 86 for task post_to_dynamics_task (Expecting value: line 1 column 2 (char 1); 14377)
[2023-06-30T11:31:48.315+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-30T11:31:48.334+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
