[2023-06-29T11:47:34.435+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: order-letter_NER.read_order_from_mail scheduled__2023-06-28T00:00:00+00:00 [queued]>
[2023-06-29T11:47:34.448+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: order-letter_NER.read_order_from_mail scheduled__2023-06-28T00:00:00+00:00 [queued]>
[2023-06-29T11:47:34.449+0000] {taskinstance.py:1308} INFO - Starting attempt 5 of 6
[2023-06-29T11:47:34.619+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): read_order_from_mail> on 2023-06-28 00:00:00+00:00
[2023-06-29T11:47:34.653+0000] {standard_task_runner.py:57} INFO - Started process 2171 to run task
[2023-06-29T11:47:34.666+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'order-letter_NER', 'read_order_from_mail', 'scheduled__2023-06-28T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/order-letter-extraction.py', '--cfg-path', '/tmp/tmph87e6d30']
[2023-06-29T11:47:34.672+0000] {standard_task_runner.py:85} INFO - Job 30: Subtask read_order_from_mail
[2023-06-29T11:47:34.922+0000] {task_command.py:410} INFO - Running <TaskInstance: order-letter_NER.read_order_from_mail scheduled__2023-06-28T00:00:00+00:00 [running]> on host 2114e0d6603f
[2023-06-29T11:47:35.301+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Abin Jilson' AIRFLOW_CTX_DAG_ID='order-letter_NER' AIRFLOW_CTX_TASK_ID='read_order_from_mail' AIRFLOW_CTX_EXECUTION_DATE='2023-06-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-28T00:00:00+00:00'
[2023-06-29T12:22:23.973+0000] {logging_mixin.py:149} INFO - An error occurred: [Errno -3] Temporary failure in name resolution
[2023-06-29T12:44:34.880+0000] {logging_mixin.py:149} INFO - An error occurred: [Errno -3] Temporary failure in name resolution
[2023-06-29T12:47:07.764+0000] {local_task_job_runner.py:291} WARNING - State of this instance has been externally set to None. Terminating instance.
[2023-06-29T12:47:07.801+0000] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 2171. PIDs of all processes in the group: [2171]
[2023-06-29T12:47:07.806+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 2171
[2023-06-29T12:47:07.809+0000] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-06-29T12:47:07.811+0000] {logging_mixin.py:149} INFO - An error occurred: Task received SIGTERM signal
[2023-06-29T12:48:07.394+0000] {process_utils.py:149} WARNING - process psutil.Process(pid=2171, name='airflow task ru', status='sleeping', started='11:47:34') did not respond to SIGTERM. Trying SIGKILL
[2023-06-29T12:48:07.396+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGKILL to group 2171
[2023-06-29T12:48:07.423+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2171, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='11:47:34') (2171) terminated with exit code Negsignal.SIGKILL
[2023-06-29T12:48:07.424+0000] {standard_task_runner.py:172} ERROR - Job 30 was killed before it finished (likely due to running out of memory)
